#!/bin/sh

SSID="$1"
if [ -z "$SSID" ]; then
  echo "Enter your SSID (Your SSID must not include spaces):"
  read SSID
fi
[ -z "$SSID" ] && exit 1

PASS="$2"
if [ -z "$PASS" ]; then
  echo "Enter your Wi-Fi password:"
  read PASS
fi
if [ "${#PASS}" -lt "8" ] || [ "${#PASS}" -gt "63" ]; then
  echo "Passphrase must be 8..63 characters"
  exit 1
fi

wificonf_h(){
  echo 'ctrl_interface=/media/bleemsync/etc/wpa_supplicant/'
  echo 'update_config=1'
  echo
}

wificonf_d(){
  wificonf_h
  echo 'network={'
  echo '}'
}

wificonf(){
  wificonf_h
  wpa_passphrase ${1+"$@"} | grep -Fv '#'
}

conf="/media/bleemsync/etc/wpa_supplicant/wpa_supplicant.conf"
wificonf "$SSID" "$PASS" > "$conf" && ret=true || ret=false
$ret || wificonf_d > "$conf"

$ret && echo "Details entered. You can reset your console now.
" | xargs | fold -s || echo "dafaq"
$ret
